---
sidebar: sidebar 
permalink: reference-google-support.html 
keywords: google, gcp, regions, google regions, gcp regions, storage class, standard, nearline, coldline, archive 
summary: Cloud Tiering admite varias clases de almacenamiento de Google Cloud y la mayoría de regiones. 
---
= Clases y regiones de almacenamiento compatibles con Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Tiering admite varias clases de almacenamiento de Google Cloud y la mayoría de regiones.



== Clases de almacenamiento de GCP admitidas

Cuando configura la organización en niveles de datos en GCP, Cloud Tiering utiliza automáticamente la clase de almacenamiento _Standard_ para sus datos inactivos. La organización en niveles del cloud puede aplicar una regla de ciclo de vida para que los datos se transiciones desde la clase de almacenamiento _Standard_ a otras clases de almacenamiento después de un cierto número de días. Puede elegir entre las siguientes clases de almacenamiento:

* Nearline
* Coldline
* Archivado


Si no selecciona otra clase de almacenamiento, los datos permanecerán en la clase de almacenamiento _Standard_ y no se aplicarán reglas.

Cuando configura una regla del ciclo de vida de Cloud Tiering, no debe configurar ninguna regla del ciclo de vida al configurar el bloque en su cuenta de Google.

https://cloud.google.com/storage/docs/storage-classes["Obtenga información sobre las clases de Google Cloud Storage"^].



== Regiones compatibles de Google Cloud

Cloud Tiering admite las siguientes regiones.



=== América

* Iowa
* Los Ángeles
* Montreal
* N. Virginia
* Oregón
* Sao Paulo
* Carolina del Sur




=== Asia-Pacífico

* Hong Kong
* Bombay
* Osaka
* Singapur
* Sídney
* Taiwán
* Tokio




=== Europa

* Bélgica
* Finlandia
* Frankfurt
* Londres
* Países Bajos
* Zurich

